### ISSUE TITLE
Current status of CEOPieceMaker incompatible with current state of Chess Evolved Online.

### ISSUE THREAD

**Issue by f300xen** [CEOPieceMaker/ceopiecemaker.github.io#10]
Please delete this fanmade Chess Evolved Online piece maker to save server space for GitHub, because Chess Evolved Online is in a state colloquially referred to as a "dead game", and so there will be very little use gotten out of this Chess Evolved Online piece maker.

**Comment by Logo121** [comment]
Will consider.
