### ISSUE TITLE
"Save Image To Computer" doesn't save piece art.

### ISSUE THREAD

**Issue by James1011R** [CEOPieceMaker/ceopiecemaker.github.io#3]
A minor bug, but sadly a bug nonetheless.

[Screenshot](https://i.imgur.com/3AKDpQ4.jpg)
[Saved](https://i.imgur.com/om3OmiS.png)

**Comment by Logo121** [comment]
seems to be external issue

https://github.com/cburgmer/rasterizeHTML.js/issues/194

**Comment by CEOPieceMaker** [comment]
temporarily fixed

![piecemaker-firefax](https://user-images.githubusercontent.com/32389043/31344000-f5fde790-ad43-11e7-9d0b-923d2fbeae85.png)

**Comment by James1011R** [comment]
thanks
